### ISSUE TITLE
Won't load on lxplus

### ISSUE THREAD

**Issue by neggert** [dmwm/cmssh#28] opened 2012-07-02 23:19 UTC
```

~: /afs/cern.ch/work/v/valya/public/soft/bin/cmssh                                                                                                                                                        õ
Welcome to cmssh! Loading configuration, please wait ...
Loading external/apt ... DONE
Loading lcg/root ... DONE
Loading external/python ... DONE
Loading external/xz ... DONE
Loading external/pcre ... DONE
Loading external/py2-matplotlib ... DONE
Loading external/py2-numpy ... DONE
Loading external/libpng ... DONE
Loading external/lapack ... DONE
Loading external/libjpg ... DONE
Loading external/libtiff ... DONE
Loading external/libungif ... DONE
Traceback (most recent call last):
  File "/afs/cern.ch/user/v/valya/workspace/public/soft/install/bin/ipython", line 8, in <module>
    load_entry_point('ipython==0.12.1', 'console_scripts', 'ipython')()
  File "/afs/cern.ch/user/v/valya/workspace/public/soft/install/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 318, in load_entry_point
  File "/afs/cern.ch/user/v/valya/workspace/public/soft/install/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 2221, in load_entry_point
  File "/afs/cern.ch/user/v/valya/workspace/public/soft/install/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 1954, in load
  File "/afs/cern.ch/user/v/valya/workspace/public/soft/install/lib/python2.6/site-packages/IPython/__init__.py", line 43, in <module>
    from .config.loader import Config
  File "/afs/cern.ch/user/v/valya/workspace/public/soft/install/lib/python2.6/site-packages/IPython/config/loader.py", line 26, in <module>
    from IPython.external import argparse
  File "/afs/cern.ch/user/v/valya/workspace/public/soft/install/lib/python2.6/site-packages/IPython/external/argparse/__init__.py", line 10, in <module>
    from _argparse import *
  File "/afs/cern.ch/user/v/valya/workspace/public/soft/install/lib/python2.6/site-packages/IPython/external/argparse/_argparse.py", line 98, in <module>
    from gettext import gettext as _
  File "/afs/cern.ch/cms/slc5_amd64_gcc462/external/python/2.6.4-cms/lib/python2.6/gettext.py", line 49, in <module>
    import locale, copy, os, re, struct, sys
  File "/afs/cern.ch/user/v/valya/workspace/public/soft/install/lib64/python2.6/locale.py", line 202, in <module>
    import re, operator
ImportError: /afs/cern.ch/user/v/valya/workspace/public/soft/install/lib64/python2.6/lib-dynload/operator.so: undefined symbol: _PyUnicodeUCS2_AsDefaultEncodedString
```

**Comment by vkuznet** [comment] 2012-07-03 14:53
Hi Nic,
sorry for that. I switched to full 64-bit build and did not check the shell from another node. Turns out that I missed LD_LIBRARY_PATH which cause python to pick-up wrong library set. The problem is fixed now and my lxplus build works for me on different nodes.

**Closed as completed by vkuznet** 2012-07-03 14:53 UTC
