### ISSUE TITLE
Installation on lxplus

### ISSUE THREAD

**Issue by demattia** [dmwm/cmssh#53] opened 2013-09-11 21:55 UTC
While trying to install CMSSH on lxplus following the instructions listed here:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookCmsshTutorial#InSt
I get an error:
Install pip
Fail at line '/bin/sh: /afs/cern.ch/user/d/demattia/work/CMSSH/soft/install/bin/pip: No such file or directory
'
need more than 1 value to unpack
Traceback (most recent call last):
  File "cmssh_install.py", line 1247, in <module>
    main()
  File "cmssh_install.py", line 790, in main
    pkg, ver = line.replace('\n', '').split('==')
ValueError: need more than 1 value to unpack

To reproduce the issue from an lxplus5 machine:
curl -k https://raw.github.com/dmwm/cmssh/master/cmssh_install.py > cmssh_install.py
source /afs/cern.ch/cms/slc5_amd64_gcc462/external/python/2.6.4-cms/etc/profile.d/init.sh
python cmssh_install.py --install --dir=$PWD --arch=slc5_amd64_gcc462 --cmssw=/afs/cern.ch/cms --multi-user

**Comment by vkuznet** [comment] 2013-09-12 13:48
Hi, I was able to reproduce and fix the problem. The issue was with a change of install procedure with one of the underlying packages. I pushed all changes to the master and you should be able to re-try again. You'll need to download fresh copy of cmssh_install.py from the link you used. Please note that --multi-user option is not required in your case, since you're installing the tool in your private area (not system wise under the root). Please report how installation will go under this ticket.
Valentin.

**Comment by demattia** [comment] 2013-09-12 15:27
Hi, I tested it and it worked perfectly. Thank you very much for the fast fix!
The only extra bit was the missing jinja2 package for opening a notebook. I installed it via pip from the cmssh shell and everything worked fine.

**Comment by vkuznet** [comment] 2013-09-12 15:35
Ok, I'll add jinja2 package to the list of dependencies and will close this ticket once it's there.

**Comment by vkuznet** [comment] 2013-09-12 19:17
Added jinja2, closing the ticket

**Closed as completed by vkuznet** 2013-09-12 19:17 UTC
